### ISSUE TITLE
Error while running test

### ISSUE THREAD

**Issue by thanhtin1997** [Seanseattle/SMIS#2]
I use win10 pytorch 1.0.0, torchvision 0.2.2.post3, I try pytorch 1.4.0, torchvision 0.5.0 same error.
I add DeepFashion Dataset and pretrained
Run test:
python test.py --name deepfashion_smis --dataset_mode deepfashion --dataroot D:/dataset/deepfashion --no_instance --gpu_ids 0 --ngf 160 --batchSize 4 --model smis --netE conv --netG deepfashion
Error:
![image](https://user-images.githubusercontent.com/31279792/79679474-7dde8e80-8230-11ea-8c22-3af3e5607014.png)
Please support help me!

**Comment by Seanseattle** [comment]
The --use_vae parameter is missing at your scripts. As the --use_vae is always needed, I will set this parameter default is true.

**Comment by thanhtin1997** [comment]
Thanks for the reply, I tested and will report back soon

**Comment by thanhtin1997** [comment]
The result has been, thank you so much for your support.
